using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="CourseTest.ChangeTo.g.cs">Copyright ©  2014</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace CSharp
{
    public partial class CourseTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CourseTest))]
public void ChangeTo704()
{
    Course course;
    Teacher teacher;
    course = CourseFactory.Create((string)null, 0, (Teacher)null);
    teacher = TeacherFactory.Create((string)null);
    this.ChangeTo(course, teacher);
    Assert.IsNotNull((object)course);
    Assert.IsNotNull(course.Teacher);
    Assert.AreEqual<string>((string)null, course.Teacher.Name);
    Assert.AreEqual<int>(1, course.Teacher.HourlyRate);
    Assert.AreEqual<string>((string)null, course.Subject);
    Assert.AreEqual<int>(0, course.Hours);
}
[TestMethod]
[PexGeneratedBy(typeof(CourseTest))]
[ExpectedException(typeof(Exception))]
public void ChangeToThrowsException189()
{
    Course course;
    course = CourseFactory.Create((string)null, 0, (Teacher)null);
    this.ChangeTo(course, (Teacher)null);
}
    }
}
