using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="CourseTest.VerifiedChangeTo.g.cs">Copyright ©  2014</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace CSharp
{
    public partial class CourseTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CourseTest))]
public void VerifiedChangeTo796()
{
    Course course;
    course = CourseFactory.Create((string)null, 0, (Teacher)null);
    this.VerifiedChangeTo(course, (Teacher)null);
    Assert.IsNotNull((object)course);
    Assert.IsNull(course.Teacher);
    Assert.AreEqual<string>((string)null, course.Subject);
    Assert.AreEqual<int>(0, course.Hours);
}
[TestMethod]
[PexGeneratedBy(typeof(CourseTest))]
public void VerifiedChangeTo548()
{
    Teacher teacher;
    Course course;
    teacher = TeacherFactory.Create((string)null);
    course = CourseFactory.Create((string)null, 0, teacher);
    this.VerifiedChangeTo(course, (Teacher)null);
    Assert.IsNotNull((object)course);
    Assert.IsNull(course.Teacher);
    Assert.AreEqual<string>((string)null, course.Subject);
    Assert.AreEqual<int>(0, course.Hours);
}
    }
}
